### ISSUE TITLE
Sandbox 'Calling generated workflows' docs

### ISSUE THREAD

**Issue by bzier** [stackfoundation/issues#3]
The sandbox workflow documentation section '[Calling generated workflows](https://stack.foundation/#!/docs/workflows#generated)' indicates that it:
>is done using the `generator` property, which is used instead of the `script` property

However, the example still uses the `script` property for the step. This seems incorrect, unless I am misunderstanding the behavior.

**Comment by rchodava** [comment]
You are right bzier - there is a mistake in that example in the docs. It should be using the `generator` property. Did you have trouble calling generated workflows? Thanks for reporting, will fix.

**Comment by bzier** [comment]
I haven't tried yet. I was just reading through the docs this morning. I'm not sure I have a use case for that feature at the moment, but just noticed it was a confusing disparity between the description and the example

**Comment by rchodava** [comment]
Updated the docs to fix, thanks for reporting.

**Comment by bzier** [comment]
👍
